name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    name: build for Windows PHP 8.3
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Build the extension
        uses: php/php-windows-builder/extension@v1
        with:
          #extension-url: https://github.com/xdebug/xdebug
          #extension-ref: '3.3.1'
          php-version: '8.3'
          ts: nts
          arch: x64
          args: --enable-xdebug
          libs: zlib
    
