name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    name: build for Windows PHP 8.3
    steps:
      - name: Build the extension
        uses: php/php-windows-builder/extension@5106db21e6a35781bff937be3c9e1e56d7b17789
        with:
          #extension-url: https://github.com/xdebug/xdebug
          #extension-ref: '3.3.1'
          php-version: '8.3'
          ts: nts
          run-tests: false
          arch: x64
          args: --enable-spx
          libs: zlib
    
